name: AdvancedNotifications
main: com.m0pt0pmatt.advancednotifications.AdvancedNotifications
version: 0.4
softdepend: [PluginUtils, MenuService]
commands:
    register:
        description:
        usage:
    validate:
        description:
        usage:
    inbox:
        description:
        usage:
    sendmsg:
        description:
        usage:
    block:
        description:
        usage:
    unblock:
        description:
        usage:
    blockedplayers:
        description:
        usage:
